name: Deploy Website from Forks

on:
  push:
    branches:
      - main

jobs:
  update-gemfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Ensure Linux platform is added to Bundler
        run: |
          bundle lock --add-platform x86_64-linux
          git add Gemfile.lock
          if git diff --cached --quiet; then
            echo "No Gemfile.lock changes detected."
          else
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "Add Linux platform to Gemfile.lock"
            git push
          fi

      - name: Install dependencies
        run: bundle install

  deploy:
    needs: update-gemfile
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Build the website
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages (Fork-Friendly)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
