name: Generate Gemfile and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # Replace with your default branch name

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Allow the GITHUB_TOKEN to push to the repository

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Use the Ruby version compatible with your Jekyll project

    - name: Generate Gemfile if it doesn't exist
      run: |
        if [ ! -f Gemfile ]; then
          echo "Generating Gemfile..."
          cat <<EOL > Gemfile
source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "jekyll-feed", "~> 0.17.0"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
EOL
          echo "Gemfile generated"
        else
          echo "Gemfile already exists"
        fi

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site
      run: bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
